### ISSUE TITLE
Alternative means for unicode entry? -- get_wch only supported in python 3.3

### ISSUE THREAD

**Issue by firecat53** [raymontag/keepassc#31]
Hey, just wondering if there was a different way to support Unicode entry besides get_wch, which is only supported in python 3.3. That's automatically going to increase your potential user base, as a lot of people only use python 2.7, and even ubuntu is only up to 3.2 (in the repos) in their LTS release.

Scott

**Comment by raymontag** [comment]
This shouldn't be a problem anymore, even Debian oldstable is abobe 3.3
